### ISSUE TITLE
form builder overlay for select items 

### ISSUE THREAD

**Issue by doomlab** [STAPLE-verse/STAPLE#242]
<img width="1175" alt="image" src="https://github.com/user-attachments/assets/c1250911-37e2-4652-b117-2addc8369098">

When creating/editing a form (forms -> create or edit) this damned box will not overlay on top. Here's what it should do from bootstrap:

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/2da965f2-c9e8-49fa-9bab-84738c5cff19">

**Comment by chartgerink** [comment]
![CleanShot 2024-09-02 at 20 56 40@2x](https://github.com/user-attachments/assets/af50047d-7e11-402e-8bc0-8b0e6aa9baf2)

After some digging, it looks like the `overflow: hidden` element on the `.collapse` is the root cause of this issue (tested on https://app.staple.science). 

I believe the [`.collapse` class originates from the UI library, `daisyUI`](https://daisyui.com/components/collapse/), but where exactly this change happens in the application I have not been able to find. Maybe @marton-balazs-kovacs has more insight on this?

**Comment by doomlab** [comment]
<img width="1234" alt="image" src="https://github.com/user-attachments/assets/83426b3d-8a41-4b9d-9a6a-40e1dafd6478">

You are a magician! I knew exactly where that css was - thanks!
